columnSuffix: zjrnzyro
contentColumnType: text
fieldGroup: 4a8eafed-2ccc-4f41-a00e-05cfe40dc81c # Homepage
handle: heroTitle
instructions: ''
name: 'Hero Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
