columnSuffix: null
contentColumnType: string
fieldGroup: 4a8eafed-2ccc-4f41-a00e-05cfe40dc81c # Homepage
handle: heroImage
instructions: ''
name: 'Hero Image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:6de9e057-d31a-4285-921e-461acdbe4c16' # Home
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:6de9e057-d31a-4285-921e-461acdbe4c16' # Home
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
