columnSuffix: null
contentColumnType: string
fieldGroup: 4bf72f84-66f5-4fa9-b622-20b6c6a2f75f # Common
handle: photos
instructions: ''
name: Photos
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:6de9e057-d31a-4285-921e-461acdbe4c16' # Home
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: 'Add a photo'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:6de9e057-d31a-4285-921e-461acdbe4c16' # Home
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
