columnSuffix: null
contentColumnType: string
fieldGroup: e1cc0527-d367-4bdc-b387-10712174540c
handle: riders
instructions: ''
name: Riders
searchable: false
settings:
  contentTable: '{{%matrixcontent_riders}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
